# Generated by Django 3.1.7 on 2021-03-11 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('recipient_phone', models.CharField(max_length=13)),
                ('recipient_name', models.CharField(max_length=50)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('event_date', models.DateField()),
                ('amount_spent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payement_method', models.CharField(max_length=40)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'expenditure',
            },
        ),
    ]
