# Generated by Django 3.1.7 on 2021-03-12 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_expenditure'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_offered', models.CharField(max_length=32)),
                ('payer_contact', models.CharField(max_length=13)),
                ('payer_name', models.CharField(max_length=50)),
                ('payment_method', models.CharField(max_length=20)),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('amount_received', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'revenue',
            },
        ),
    ]
